version: '3'

services:
  codef-server:
    build:
      context: io-server/
      dockerfile: Dockerfile-prod
    container_name: codef-server
  codef-client:
    build:
      context: io-client/
      dockerfile: Dockerfile
  # redis-main:
  #   image: redis
  #   container_name: redis-main
  #   ports:
  #     - 6380:6379
  #   networks:
  #     - redisNet
